MvcApiNuggetTiendaZapatillasJPL/Models/ErrorViewModel.cs
namespace MvcApiNuggetTiendaZapatillasJPL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiNuggetTiendaZapatillasJPL/Models/LoginModel.cs
namespace MvcApiNuggetTiendaZapatillasJPL.Models
{
    public class LoginModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

MvcApiNuggetTiendaZapatillasJPL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiNuggetTiendaZapatillasJPL.Models;
using System.Diagnostics;

namespace MvcApiNuggetTiendaZapatillasJPL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiNuggetTiendaZapatillasJPL/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcApiNuggetTiendaZapatillasJPL.Services;
using Newtonsoft.Json;
using NuggetTiendaZapatillasJPL.Models;
using System.Security.Claims;

namespace MvcApiNuggetTiendaZapatillasJPL.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceApiUsuarios service;

        public ManagedController(ServiceApiUsuarios service)
        {
            this.service = service;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login
     (string email, string password)
        {
            string token =
                await this.service.GetTokenAsync(email, password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Email/Password incorrectos";
                return View();
            }
            else
            {
                ViewData["MENSAJE"] = "Bienvenid@ a mi App!!!";
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity
                    (CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.Name, email));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, password));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                    });
                return RedirectToAction("Index", "Zapatillas");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register(string nombre, string dni, string direccion, string telefono, string email, byte[] password)
        {
            await this.service.InsertUsuarioAsync(nombre, dni, direccion,telefono, email, password);
            return RedirectToAction("Index", "Zapatillas");
        }

        [Authorize]
        [HttpGet]
        [Route("[action]")]
        public async Task<ActionResult<Usuario>> PerfilUsuario()
        {
            string token =
                HttpContext.Session.GetString("TOKEN");
            Usuario user = await
                this.service.GetPerfilUsuarioAsync(token);
            return View(user);
        }
    }
}

MvcApiNuggetTiendaZapatillasJPL/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiNuggetTiendaZapatillasJPL.Services;
using NuggetTiendaZapatillasJPL.Models;

namespace MvcApiNuggetTiendaZapatillasJPL.Controllers
{
    public class ZapatillasController : Controller
    {
        private ServiceApiZapatillas service;

        public ZapatillasController(ServiceApiZapatillas service)
        {
            this.service = service;
        }


        //METODO PARA SACAR TODAS LAS ZAPAS
        public async Task<IActionResult> Index()
        {

            List<Zapatilla> cubos =
                await this.service.GetZapatillassAsync();
            return View(cubos);

        }

        //METODO PARA BUSCAR CUBO POR MARCA
        public async Task<IActionResult> FindCuboAsync(int id)
        {
            Zapatilla zapa = await this.service.FindZapatillaAsync(id);
            return View(zapa);
        }
    }
}

MvcApiNuggetTiendaZapatillasJPL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiNuggetTiendaZapatillasJPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiNuggetTiendaZapatillasJPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiNuggetTiendaZapatillasJPL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiNuggetTiendaZapatillasJPL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcApiNuggetTiendaZapatillasJPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcApiNuggetTiendaZapatillasJPL/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false){
    <li class="nav-item">
        <a class="nav-link text-dark" 
            asp-controller="Managed" 
            asp-action="PerfilUsuario">
            Amigo no identificado
        </a>
    </li>
}else{
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Managed"
            asp-action="LogOut">
            Log Out <span style="color:salmon">
                @Context.User.Identity.Name
            </span>
        </a>
    </li>
}